remove setting baggaeclaim driver for k8s deploy
after bumping to ubuntu jammy k8s-topgun, worker pod starts with

ERROR: not a btrfs filesystem: /concourse-work-dir
ERROR: can't access '/concourse-work-dir'

Signed-off-by: Rui Yang <ruiya@vmware.com>